TB-step_8 use Regex for parsing, create class TelegramBotService and …
DTigrusha/LearnEnglishWordsTelegramBot pull request #10
Opened 2023-06-15 07:53 UTC by DTigrusha

…two functions in it, configure message "Hello" exchange

2023-06-15 13:41 UTC, ievetrov requested changes

2023-06-15 13:41 UTC, ievetrov commented on src/main/kotlin/telegram_bot/Telegram.kt
> +        val updateIdRegex: Regex = "\"update_id\":(.+?),".toRegex()
Нам не нужно создавать regex каждую итерацию цикла. Всегда когда работаешь с циклами, старайся выносить то, что можно выносить

2023-06-15 13:41 UTC, ievetrov commented on src/main/kotlin/telegram_bot/TelegramBotService.kt
> +    fun getUpdates(botToken: String, updateId: Int): String {
botToken можно вынести в основной конструктор класса TelegramBotService()

2023-06-15 13:41 UTC, ievetrov commented on src/main/kotlin/telegram_bot/TelegramBotService.kt
> +        val urlSendMessage = "https://api.telegram.org/bot$botToken/sendMessage?chat_id=$chatId&text=$messageText"
https://api.telegram.org/bot - можно вынести в константу:

```Kotlin
class TelegramBotService {
    // ...
    companion {
      const val СЮДА <<<
    }
}

```

2023-06-16 08:50 UTC, DTigrusha commented on src/main/kotlin/telegram_bot/TelegramBotService.kt
> +        val urlSendMessage = "https://api.telegram.org/bot$botToken/sendMessage?chat_id=$chatId&text=$messageText"
Не совсем поняла - этот комментарий относился к БотТокену как альтернативный вариант переноса? Не смогла разобраться, как инициализировать константу, не показывая значение токена.

2023-06-16 17:58 UTC, ievetrov commented on src/main/kotlin/telegram_bot/TelegramBotService.kt
> +        val urlSendMessage = "https://api.telegram.org/bot$botToken/sendMessage?chat_id=$chatId&text=$messageText"
Нет ) я имел в виду строку "https://api.telegram.org/bot" - ее можно вынести в константу, она же повторяется в каждом запросе

2023-06-17 11:58 UTC, ievetrov approved these changes
Идеально

2023-06-17 12:41 UTC, merged