TB-step_10 finalize telegram bot
DTigrusha/LearnEnglishWordsTelegramBot pull request #12
Opened 2023-06-22 08:30 UTC by DTigrusha

2023-06-22 12:15 UTC, ievetrov requested changes
Тааак ) Давай для начала наведем порядок:
1. Я переключился на твою ветку и попытался собрать jar командой `./gradlew shadowJar`, увидел вот такой ворох ошибок:
<img width="1376" alt="Screenshot 2023-06-22 at 15 06 06" src="https://github.com/DTigrusha/LearnEnglishWordsTelegramBot/assets/34489023/b4bcd33b-55ce-4cec-b7f8-c3d4aa5e5626">

При ближайшем рассмотрении увидел неправильные имена пакетов:
<img width="507" alt="Screenshot 2023-06-22 at 15 06 02" src="https://github.com/DTigrusha/LearnEnglishWordsTelegramBot/assets/34489023/59c53ada-b995-4c74-a05e-45b1d44c0a14">
<img width="681" alt="Screenshot 2023-06-22 at 15 06 25" src="https://github.com/DTigrusha/LearnEnglishWordsTelegramBot/assets/34489023/7d8d1b97-4e46-4092-9141-25cace2729f0">

И еще два класса LearnWordsTrainer. Одно из основных преимуществ вынесения кода в классы, это переиспользование кода. Давай оставим только один LearnWordsTrainer, а тот который в console_version удалим. Также удалим класс Word из LearnEnglishWords_TB_consoleVersion.kt. И содержимое telegram_bot тоже нам не нужно, будет нас только путать. 
Теперь починим консольный тренажер, импортировав нужные классы и вызвав конструктор с параметрами вот так:
<img width="768" alt="Screenshot 2023-06-22 at 15 18 39" src="https://github.com/DTigrusha/LearnEnglishWordsTelegramBot/assets/34489023/0a20705b-6312-4410-9b71-4ddbbd8ff22b">

2) После этого все успешно соберется, но при попытке запустить консольный тренажер (кнопка Run рядом с `fun main()` увидим ошибку:

<img width="870" alt="Screenshot 2023-06-22 at 15 20 21" src="https://github.com/DTigrusha/LearnEnglishWordsTelegramBot/assets/34489023/b0b1bebc-ecc9-4aa9-9165-23d96dc64902">

Проблема в лишних переносах в файле words.txt. 
<img width="540" alt="Screenshot 2023-06-22 at 15 21 22" src="https://github.com/DTigrusha/LearnEnglishWordsTelegramBot/assets/34489023/e3ec2267-8407-4cdb-a951-45513bf46ef3">

Можем их просто удалить, но лучше поправить LearnWordsTrainer, чтобы он игнорировал некорректные строки, достаточно убедится, что split в методе loadDictionary() возвращает ровно 3 элемента, только тогда делать dictionary.add(...)

3) А вот теперь можем снова проверить:
```bash
./gradlew shadowJar
 java -jar build/libs/LearnEnglishWordsTelegramBot-1.0-SNAPSHOT-all.jar тут_твой_токен
```

2023-06-22 21:04 UTC, ievetrov requested changes
Да, теперь хорошо. Осталась пара замечаний

2023-06-22 21:04 UTC, ievetrov commented on src/main/kotlin/TelegramBotService.kt
> +        if (trainer.getNextQuestion() == null) {
Тут лучше не передавать trainer, а ограничится Question'ом. Вообще старайся в параметры передавать максимально "распакованные" объекты

2023-06-22 21:04 UTC, ievetrov commented on src/main/kotlin/TelegramBotService.kt
> +                listOf(question.listOfAnswers.mapIndexed { index, word ->
1) Если слова будут подлиннее, они могут не влезть в ряд кнопок. Давай разместим кнопки столбиком - друг под другом.
2) Нужно добавить после вариантов ответов кнопку "В меню", иначе нет удобного способа приостановить обучение

2023-06-22 21:04 UTC, ievetrov commented on src/main/kotlin/Telegram.kt
> +        val responseString: String = telegramBot.getUpdates(lastUpdateId)
тут лучше добавить try / catch для вызова getUpdates(), так как если вдруг сервер телеграмм ответит на один из запросов с ошибкой, приложение упадет, так как не сможет распарсить ответ сервера.
Вместо try/catch можно воспользоваться функцией `runCatching {...}`

2023-06-23 12:01 UTC, DTigrusha commented on src/main/kotlin/Telegram.kt
> +        val responseString: String = telegramBot.getUpdates(lastUpdateId)
Не совсем уверена в правильности размещения runCatching {}

2023-06-23 12:11 UTC, DTigrusha commented on src/main/kotlin/TelegramBotService.kt
> +        if (trainer.getNextQuestion() == null) {
Заметила еще один недостаток. При добавлении новых слов в words.txt пользовательский словарь не обновляется.
Идея  такая:
1. Добавить проверку на соответствие размеров файлов со словами (общего и пользовательского).
2. Если размер пользовательского файла меньше, сообщить пользователю, что в базу добавлены новые слова и предложить обновить его словарь (либо делать это автоматически и просто сообщать пользователю об обновлении базы и добавлении новых слов).
3. Добавить функцию обновления пользовательского файла. В ней проверить наличие каждого элемента из общего словаря по первому слову (englishWord) в пользовательском файле и дополнить файл отсутствующими элементами.

2023-06-23 15:46 UTC, ievetrov requested changes

2023-06-23 15:46 UTC, ievetrov commented on src/main/kotlin/Telegram.kt
> +    runCatching {
тут не правильно. У тебя при возникновении ошибки приложение выйдет из цикла и приложение завершит работу.

```Kotlin
val result = runCatching { telegramBot.getUpdates(lastUpdateId) }
val responseString: String = result.getOrNull() ?: continue
```

2023-06-23 15:46 UTC, ievetrov commented on src/main/kotlin/Telegram.kt
> +        val responseString: String = telegramBot.getUpdates(lastUpdateId)
ответил ниже

2023-06-23 15:46 UTC, ievetrov commented on src/main/kotlin/TelegramBotService.kt
> +        if (trainer.getNextQuestion() == null) {
Да, хорошая идея! А Когда делать эту проверку, каждую итерацию цикла? При получении сообщения от пользователя?

В целом, можешь править прямо в этом этапе, а можем доделать все остальные правки и закрыть основную часть курса.

После нее я предлагаю несколько идей по развитию бота, или же принципиально свою идею для проекта, которую студент присылает на проверку как и курсовую, получает фитбек в пул реквестах

2023-06-26 06:19 UTC, DTigrusha commented
"Да, хорошая идея! А Когда делать эту проверку, каждую итерацию цикла? При получении сообщения от пользователя?"

Пока вижу эту проверку при нажатии кнопки "Изучить слова". Пользователь нажимает кнопку, сначала вызывается функция сравнения файлов. Если файл пользователя не соответствует размеру общего файла, запускается функция обновления файла. Затем запускается функция проверки и отправки вопроса. Если размеры файлов совпадают, то бот возвращает вопрос с вариантами ответа.

2023-06-26 16:24 UTC, ievetrov approved these changes
![giphy](https://github.com/AndreyDemuhDev/MyEnglishDictionaryBot/assets/34489023/b23723c1-4efd-4416-bc69-d76a96f11dd4)

Круто. С первого раза и работает, не прикопаться :D

Основная часть работы пройдена!

Теперь этот бот твой - можешь развивать его как хочешь.
До конца подписки еще остается время, так что свои идеи и ссылки на PR можешь присылать мне в личку в телеграм [@ievetrov](https://t.me/ievetrov) - посмотрю и дам обратную связь.

Круто что появилась своя идея, вот еще пара идей от меня:
- Добавить возможность показывать картинку в качестве подсказки к изучаемому слову (можно даже делать ее заблюреной - такая фича в телеграме)
- Загрузка своего словаря. Ты нажимаешь кнопку "Добавить слова", бот запрашивает файл. Отправляешь - и словарь пополняется (это кстати дополняет твою доработку)

2023-06-27 05:48 UTC, merged